# Generated by Django 5.1 on 2024-08-26 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountability_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='time',
        ),
    ]
