# Generated by Django 5.1 on 2024-08-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability_app', '0003_rename_date_event_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('created_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountability_app.event')),
            ],
        ),
    ]
