# Generated by Django 5.1 on 2024-08-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability_app', '0007_daymodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymodel',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
