# Generated by Django 5.1 on 2024-08-27 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountability_app', '0002_rename_end_time_event_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start_date',
        ),
    ]
