# Generated by Django 5.1 on 2024-08-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability_app', '0004_daymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daymodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='daymodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
